project_id = "kstugxtmghinprrpkrud"

[api]
enabled = true
port = 54321
schemas = ["public", "graphql_public"]
extra_search_path = ["public", "extensions"]
max_rows = 1000

[auth]
enabled = true
port = 54320
site_url = "http://localhost:3000"
additional_redirect_urls = ["https://localhost:3000"]
jwt_expiry = 3600
refresh_token_rotation_enabled = true
secure_password_change_enabled = false
enable_anonymous_users = false

[functions.notify-admin]
verify_jwt = false

[functions.create-payment-session]
verify_jwt = false

[functions.verify-payment]
verify_jwt = false