// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://jecmmlpvzihjnjnyxqgh.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImplY21tbHB2emloam5qbnl4cWdoIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTY0MDU0ODYsImV4cCI6MjA3MTk4MTQ4Nn0.mRRNcPFrGVQmm0S439rbiM4_XviXdd9zx8jtSbUFYEA";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});